config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :articles
  post 'article/:id/comments', to: 'comments#create', as: :comment_article
  get 'articles/comment/:id', to: 'comments#edit', as: :edit_comment_article
  patch 'articles/:id/like', to: 'articles#like', as: :like_article
  patch 'articles/:id/dislike', to: 'articles#dislike', as: :dislike_article
  
    #Rotas de SessionsController
    
    get 'login', to: 'seessions#new', as: :login
    post 'login', to: 'seessions#create'
    delete 'logout', to: 'seessions#destroy', as: :logout


    #ROTAS DE USERSCONTROLLERS
    get 'users', to: 'users#index', as: :users
    get 'users/new', to: 'users#new', as: :users_new
    post 'users/new', to: 'users#create'
    get 'users/:id', to: 'users#show', as: :user
    get 'users/edit/:id', to: 'users#edit', as: :users_edit
    patch 'users/edit/:id', to: 'users#update'
    delete 'user/delete/:id', to: 'users#destroy', as: :user_destroy
end

app/models/article.rb
class Article < ApplicationRecord
  mount_uploader :photo, PictureUploader
  
  belongs_to :user
  has_many :comments
  has_many :like_articles
  has_many :dislike_articles
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy, :like, :dislike]
  before_action :feeder, only: [:new, :create]
  before_action :non_logged_user
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :admin_user_correct_user, only: :destroy

  def like
    like = LikeArticle.find_by(article_id: @article.id, user_id: current_user.id)
    dislike = DislikeArticle.find_by(article_id: @article.id, user_id: current_user.id)
    if like.nil?
      LikeArticle.create(article_id: @article.id, user_id: current_user.id)
      if !dislike.nil?
      dislike.destroy
      end
    else
      like.destroy
    end
    redirect_to @article
  end
  
  def dislike
    dislike = DislikeArticle.find_by(article_id: @article.id, user_id: current_user.id)
    like = LikeArticle.find_by(article_id: @article.id, user_id: current_user.id)
    if dislike.nil?
      DislikeArticle.create(article_id: @article.id, user_id: current_user.id)
      if !like.nil?
      like.destroy
      end
    else
      dislike.destroy
    end
    redirect_to @article
  end
    
  
  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @comment = Comment.new
    @comments = @article.comments
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = current_user.articles.build(article_params)
    

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:user_id, :title, :content, :photo)
    end
   
end

def feeder
  if !current_user.feeder
    redirect_to article_path
  end
end
  
def correct_user
  if @article.user != current_user
    redirect_to article_path
  end
end

def admin_user_or_correct_user
  if !current_user.admin && current_user != @article.user
  redirect_to articles_path
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_with(model: article, local: true) do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :article_title %>
  </div>
Foto: <%= form.file_field :photo %><br />
  
  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content, id: :article_content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Articles</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.user.name %></td>
        <td><%= article.title %></td>
        <td><%= article.content %></td>
        <td><%= link_to 'Show', article %></td>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Article', new_article_path %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>





<p>
  <strong>Content:</strong>
  <%= @article.content %>
</p>
<%= link_to "Like #{@article.like_articles.count}", like_article_path, method: :patch %>
<%= link_to "Dislike #{@article.dislike_articles.count}", dislike_article_path, method: :patch %>

<%=form_for @comment, url: :comment_article do |f| %>
  <%= f.text_field :content %>
  <%= f.submit "Comentar" %> 
<% end %>
<p>Foto: <%=image_tag(@article.photo_url) if @article.photo.present?%></p>
<% @comments.each do |comment| %>
<p><%= comment.content %></p>
<p><%= link_to "Editar", edit_comment_article_path(comment) %></p>

<% end %>
<div class="center">
  <%= link_to 'Edit', edit_article_path(@article) %> |
  <%= link_to 'Back', comments_path %>
</div>