config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :articles
  post 'article/:id/comments', to: 'comments#create', as: :comment_article
  get 'articles/comment/:id', to: 'comments#edit', as: :edit_comment_article
  patch 'articles/:id/like', to: 'articles#like', as: :like_article
  patch 'articles/:id/dislike', to: 'articles#dislike', as: :dislike_article
  
    #Rotas de SessionsController
    
    get 'login', to: 'seessions#new', as: :login
    post 'login', to: 'seessions#create'
    delete 'logout', to: 'seessions#destroy', as: :logout


    #ROTAS DE USERSCONTROLLERS
    get 'users', to: 'users#index', as: :users
    get 'users/new', to: 'users#new', as: :users_new
    post 'users/new', to: 'users#create'
    get 'users/:id', to: 'users#show', as: :user
    get 'users/edit/:id', to: 'users#edit', as: :users_edit
    patch 'users/edit/:id', to: 'users#update'
    delete 'user/delete/:id', to: 'users#destroy', as: :user_destroy
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :profile_photo, PictureUploader 
  
  has_secure_password
  
  has_many :articles
  has_many :comments
  has_many :like_articles
  has_many :dislkike_articles
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only: [:show, :edit, :destroy, :update]
    before_action :logged_user, only: [:new, :create]
    before_action :non_logged_user, except: [:new, :create]
    before_action :correct_user_or_admin, only: [:edit, :update, :destroy]
    
    
    
    def new
        @user = User.new
    end
    
    def create
        
      @user = User.new(user_params)
      if @user.save
          redirect_to user_path(@user)
      else
          render :new
      end
    end
    
    def show
    end
    
    def edit
    end
    
    def index
        #Variaveis com @ são variaveis de instancia
        #elas ficam disponiveis para as views
        @users = User.all
    end
    def update
        if @user.update_attributes(user_params)
          redirect_to user_path(@user)
        else
          render :edit
        end
    end
    def destroy
       if @user == current_user
         log_out
       end
       @user.destroy
       redirect_to users_path
       
    end
end

private
def set_user
    @user = User.find(params[:id])
end
def user_params
    @user_params = params.require(:user).permit(:name, :email, :password, :password_confirmation, :feeder, :profile_photo)
    
end

    def correct_user_or_admin
      if current_user != @user && !current_user.admin
        redirect_to user_path(current_user)
      end
    end
    
    

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for @user, url: @user.persisted? ? users_edit_path : users_new_path do |f| %>
    <% if current_user && current_user == @user || !@user.persisted? %>
    Nome: <%= f.text_field :name %><br />

    Email: <%= f.text_field :email %><br />
    
    Foto: <%= f.file_field :photo %><br />
    
    Password: <%= f.password_field :password %><br />
    
    Password_Confirmation: <%= f.password_field :password_confirmation %><br />
    <%end%>
    <%if current_user && current_user.admin %>
    Gerador de conteudo: <%= f.check_box :feeder %><br />
    <%end%>
    <%= f.submit "Enviar" %>
  
<% end %>

app/views/users/edit.html.erb
<h1>Edit user</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1>Index</h1>
<% @users.each do |user| %>
  <p>Nome: <%=link_to user.name,  user_path(user)%></p>
  
  <p>Email: <%=user.email%> </p>
  <%= link_to "Apagar Usuário", user_destroy_path(user), method: :delete %>
  <hr>
<% end%>

app/views/users/new.html.erb
<h1>New</h1>

<%= render "form" %>

app/views/users/show.html.erb
<p>Nome: <%= @user.name %></p>
<p>Email: <%= @user.email %></p>
<p>Foto: <%=image_tag(@user.profile_photo_url) if @user.profile_photo.present?%></p>

<%= link_to 'Editar Usuário', users_edit_path(@user) %>